# Generated by Django 5.2.10 on 2026-04-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_created_at_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Platform Admin"),
                    ("restaurant_admin", "Restaurant Admin"),
                    ("staff", "Staff"),
                    ("kitchen", "Kitchen Staff"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
