# Generated by Django 5.2.10 on 2026-04-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
        ("restaurants", "0002_alter_restaurant_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="restaurants.restaurant",
            ),
        ),
    ]
