# Generated by Django 5.2.10 on 2026-04-06 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="owner",
            field=models.OneToOneField(
                limit_choices_to={"role": "restaurant_admin"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_restaurant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
