# Generated by Django 5.2.10 on 2026-04-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_paymentconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentconfig",
            name="merchant_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="eSewa product_code / merchant code",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="paymentconfig",
            name="secret_key",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
