# Generated by Django 4.2.30 on 2026-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_subscription_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentconfig',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='esewa_total_amount',
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='public_key',
            field=models.CharField(blank=True, default='', help_text='Khalti Public Key', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='provider',
            field=models.CharField(choices=[('khalti', 'Khalti')], default='khalti', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='secret_key',
            field=models.CharField(blank=True, default='', help_text='Khalti Secret Key', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='provider',
            field=models.CharField(choices=[('khalti', 'Khalti')], default='khalti', max_length=32),
        ),
    ]
