# Generated by Django 5.2.10 on 2026-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted by Staff"),
                    ("preparing", "In Kitchen"),
                    ("done", "Ready"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
