# Generated by Django 5.2.10 on 2026-04-11 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
    ]
