# Generated by Django 5.2.10 on 2026-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_rename_orderitem_price_to_unit_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing"),
                    ("served", "Served"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Unit price at time of order (from menu at checkout; never from client)",
                max_digits=10,
            ),
        ),
    ]
