# Generated by Django 5.2.10 on 2026-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_sync_order_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="order",
                    name="esewa_pay_total_amount",
                    field=models.CharField(blank=True, max_length=24, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $fn$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = current_schema()
                              AND table_name = 'orders_order'
                              AND column_name = 'esewa_pay_total_amount'
                        ) THEN
                            ALTER TABLE orders_order
                            ALTER COLUMN esewa_pay_total_amount DROP NOT NULL;
                        ELSE
                            ALTER TABLE orders_order
                            ADD COLUMN esewa_pay_total_amount varchar(24) NULL;
                        END IF;
                    END $fn$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
