# Generated by Django 4.2.30 on 2026-04-14 20:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menuitemcustomizationgroup_menuoffer_menuofferitem_and_more'),
        ('restaurants', '0004_subscription_models'),
        ('orders', '0012_order_ready_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE orders_order
                    ADD COLUMN IF NOT EXISTS discount_total numeric(10, 2) NOT NULL DEFAULT 0.00;

                    ALTER TABLE orders_order
                    ADD COLUMN IF NOT EXISTS subtotal_price numeric(10, 2) NOT NULL DEFAULT 0.00;

                    ALTER TABLE orders_orderitem
                    ADD COLUMN IF NOT EXISTS base_unit_price numeric(10, 2) NOT NULL DEFAULT 0.00;

                    CREATE TABLE IF NOT EXISTS orders_orderreview (
                        id bigserial PRIMARY KEY,
                        session_id varchar(64) NOT NULL,
                        customer_name varchar(255) NOT NULL DEFAULT '',
                        food_quality smallint NOT NULL,
                        service smallint NOT NULL,
                        overall_experience smallint NOT NULL,
                        comment text NOT NULL DEFAULT '',
                        created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        order_id bigint NOT NULL,
                        restaurant_id bigint NOT NULL
                    );

                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS session_id varchar(64);
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS customer_name varchar(255) NOT NULL DEFAULT '';
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS food_quality smallint;
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS service smallint;
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS overall_experience smallint;
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS comment text NOT NULL DEFAULT '';
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP;
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS order_id bigint;
                    ALTER TABLE orders_orderreview
                    ADD COLUMN IF NOT EXISTS restaurant_id bigint;

                    CREATE INDEX IF NOT EXISTS orders_orderreview_session_id_idx
                    ON orders_orderreview (session_id);

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_indexes
                            WHERE schemaname = current_schema()
                              AND tablename = 'orders_orderreview'
                              AND indexname = 'orders_orderreview_order_id_uniq'
                        ) THEN
                            CREATE UNIQUE INDEX orders_orderreview_order_id_uniq
                            ON orders_orderreview (order_id);
                        END IF;
                    END $$;

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_indexes
                            WHERE schemaname = current_schema()
                              AND tablename = 'orders_orderreview'
                              AND indexname = 'orders_unique_review_session_order_idx'
                        ) THEN
                            CREATE UNIQUE INDEX orders_unique_review_session_order_idx
                            ON orders_orderreview (restaurant_id, session_id, order_id);
                        END IF;
                    END $$;

                    CREATE TABLE IF NOT EXISTS orders_orderitemcustomizationselection (
                        id bigserial PRIMARY KEY,
                        group_name varchar(100) NOT NULL,
                        option_name varchar(100) NOT NULL,
                        price_delta numeric(8, 2) NOT NULL DEFAULT 0,
                        customization_option_id bigint NULL,
                        order_item_id bigint NOT NULL
                    );

                    ALTER TABLE orders_orderitemcustomizationselection
                    ADD COLUMN IF NOT EXISTS group_name varchar(100);
                    ALTER TABLE orders_orderitemcustomizationselection
                    ADD COLUMN IF NOT EXISTS option_name varchar(100);
                    ALTER TABLE orders_orderitemcustomizationselection
                    ADD COLUMN IF NOT EXISTS price_delta numeric(8, 2) NOT NULL DEFAULT 0;
                    ALTER TABLE orders_orderitemcustomizationselection
                    ADD COLUMN IF NOT EXISTS customization_option_id bigint;
                    ALTER TABLE orders_orderitemcustomizationselection
                    ADD COLUMN IF NOT EXISTS order_item_id bigint;

                    CREATE INDEX IF NOT EXISTS orders_orderitemcustomizationselection_order_item_id_idx
                    ON orders_orderitemcustomizationselection (order_item_id);

                    CREATE TABLE IF NOT EXISTS orders_orderappliedoffer (
                        id bigserial PRIMARY KEY,
                        name varchar(120) NOT NULL,
                        badge_text varchar(40) NOT NULL DEFAULT '',
                        offer_type varchar(16) NOT NULL,
                        discount_amount numeric(10, 2) NOT NULL DEFAULT 0,
                        offer_id bigint NULL,
                        order_id bigint NOT NULL
                    );

                    ALTER TABLE orders_orderappliedoffer
                    ADD COLUMN IF NOT EXISTS name varchar(120);
                    ALTER TABLE orders_orderappliedoffer
                    ADD COLUMN IF NOT EXISTS badge_text varchar(40) NOT NULL DEFAULT '';
                    ALTER TABLE orders_orderappliedoffer
                    ADD COLUMN IF NOT EXISTS offer_type varchar(16);
                    ALTER TABLE orders_orderappliedoffer
                    ADD COLUMN IF NOT EXISTS discount_amount numeric(10, 2) NOT NULL DEFAULT 0;
                    ALTER TABLE orders_orderappliedoffer
                    ADD COLUMN IF NOT EXISTS offer_id bigint;
                    ALTER TABLE orders_orderappliedoffer
                    ADD COLUMN IF NOT EXISTS order_id bigint;

                    CREATE INDEX IF NOT EXISTS orders_orderappliedoffer_order_id_idx
                    ON orders_orderappliedoffer (order_id);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='discount_total',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
                ),
                migrations.AddField(
                    model_name='order',
                    name='subtotal_price',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
                ),
                migrations.AddField(
                    model_name='orderitem',
                    name='base_unit_price',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Menu item unit price after item-level offers but before customization extras.', max_digits=10),
                ),
                migrations.CreateModel(
                    name='OrderReview',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('session_id', models.CharField(db_index=True, max_length=64)),
                        ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                        ('food_quality', models.PositiveSmallIntegerField()),
                        ('service', models.PositiveSmallIntegerField()),
                        ('overall_experience', models.PositiveSmallIntegerField()),
                        ('comment', models.TextField(blank=True, default='')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order')),
                        ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='OrderItemCustomizationSelection',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('group_name', models.CharField(max_length=100)),
                        ('option_name', models.CharField(max_length=100)),
                        ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                        ('customization_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menuitemcustomizationoption')),
                        ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='orders.orderitem')),
                    ],
                    options={
                        'ordering': ['id'],
                    },
                ),
                migrations.CreateModel(
                    name='OrderAppliedOffer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=120)),
                        ('badge_text', models.CharField(blank=True, default='', max_length=40)),
                        ('offer_type', models.CharField(max_length=16)),
                        ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                        ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menuoffer')),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_offers', to='orders.order')),
                    ],
                    options={
                        'ordering': ['id'],
                    },
                ),
                migrations.AddConstraint(
                    model_name='orderreview',
                    constraint=models.UniqueConstraint(fields=('restaurant', 'session_id', 'order'), name='orders_unique_review_session_order'),
                ),
            ],
        ),
    ]
