# Generated by Django 4.2.30 on 2026-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_discount_total_order_subtotal_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='esewa_pay_total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='esewa_transaction_uuid',
        ),
        migrations.AddField(
            model_name='order',
            name='khalti_pidx',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='food_quality_legacy',
            field=models.PositiveSmallIntegerField(blank=True, db_column='food_quality_rating', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='overall_experience_legacy',
            field=models.PositiveSmallIntegerField(blank=True, db_column='overall_rating', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='service_legacy',
            field=models.PositiveSmallIntegerField(blank=True, db_column='service_rating', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('khalti', 'Khalti')], max_length=16, null=True),
        ),
    ]
