# Generated by Django 4.2.30 on 2026-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='khalti_public_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='khalti_secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
