# Generated by Django 5.2.10 on 2026-04-06 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="table",
            name="qr_code",
        ),
    ]
