# Generated by Django 5.2.10 on 2026-04-06 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
        ("tables", "0002_alter_table_unique_together_remove_table_qr_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("restaurant", "number")},
        ),
    ]
