# Generated by Django 5.2.10 on 2026-04-06 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0003_alter_table_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="qr_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
