# Generated by Django 5.2.10 on 2026-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0004_table_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
