# Generated by Django 5.2.10 on 2026-02-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="is_available",
            new_name="available",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
