# Generated by Django 5.2.10 on 2026-03-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_rename_is_available_menuitem_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu/"),
        ),
    ]
