# Generated by Django 5.2.10 on 2026-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0006_menuitem_variant_split_sizes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="variant_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: Small, Large, etc. Same dish name can repeat per category with different variants.",
                max_length=50,
            ),
        ),
    ]
