# Generated by Django 4.2.30 on 2026-04-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_subscription_models'),
        ('menu', '0007_alter_menuitem_variant_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemCustomizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selection_mode', models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice')], default='single', max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('max_select', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_groups', to='menu.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('offer_type', models.CharField(choices=[('fixed', 'Fixed discount'), ('percentage', 'Percentage discount'), ('combo', 'Combo / special meal')], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('badge_text', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('combo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_offers', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_links', to='menu.menuitem')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menuoffer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemCustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.menuitemcustomizationgroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='menuofferitem',
            constraint=models.UniqueConstraint(fields=('offer', 'menu_item'), name='menu_unique_offer_item_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='menuitemcustomizationoption',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='menu_unique_customization_option_name_per_group'),
        ),
        migrations.AddConstraint(
            model_name='menuitemcustomizationgroup',
            constraint=models.UniqueConstraint(fields=('menu_item', 'name'), name='menu_unique_customization_group_name_per_item'),
        ),
    ]
